name: build

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
        registry-url: 'https://registry.npmjs.org'
    
    - name: Prepare
      run: |
        sudo apt-get install lsof
        npm install yarn -g
        npm install codecov -g
        npm install typescript -g

    - name: Install
      run: |
        yarn clean:all
        yarn install:all

    - name: Codecov
      run: codecov -t ${{ secrets.CODECOV_TOKEN }}

    - name: Build
      run: |
        yarn build:all

    - name: Test
      run: |
        yarn test

    - name: Integration Test
      run: |
        yarn cypress:prepare
        yarn cypress:test

    - name: Create version patch
      run: yarn update-version patch

    - name: Publish direflow-cli to NPM
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
  
    - name: Publish direflow-component to NPM
      run: |
        cd packages/direflow-component
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
  