name: test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container: cypress/included:3.8.3
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
        browser: chrome
    
    - name: Prepare
      run: |
        npm install yarn -g
        npm install typescript -g

    - name: Install
      run: |
        yarn clean:all
        yarn install:all
        
    - name: Build
      run: |
        yarn build:all

    - name: Test
      run: |
        yarn test

    - name: Integration Test
      run: |
        yarn cypress:test

    - name: Integration Test
      run: |
        yarn cypress:test
